# Generated by Django 3.0.8 on 2020-08-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basic_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Companyname', models.CharField(max_length=100, null=True)),
                ('CompanyNumber', models.CharField(max_length=100, null=True)),
                ('CompanyWebsite', models.CharField(max_length=100, null=True)),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('Designation', models.CharField(max_length=100, null=True)),
                ('mobile_number', models.IntegerField(null=True)),
                ('CompanyCategory', models.CharField(max_length=100, null=True)),
                ('CompanyType', models.CharField(max_length=100, null=True)),
                ('CompanySize', models.CharField(max_length=100, null=True)),
                ('CompanyRevenue', models.CharField(max_length=100, null=True)),
                ('FacebookLink', models.CharField(max_length=100, null=True)),
                ('TwitterLink', models.CharField(max_length=100, null=True)),
                ('LinkedIN', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
