# Generated by Django 3.0.8 on 2020-08-04 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_detail',
            name='CompanyCategory',
        ),
        migrations.RemoveField(
            model_name='basic_detail',
            name='CompanyRevenue',
        ),
        migrations.RemoveField(
            model_name='basic_detail',
            name='CompanySize',
        ),
        migrations.RemoveField(
            model_name='basic_detail',
            name='CompanyType',
        ),
        migrations.RemoveField(
            model_name='basic_detail',
            name='Designation',
        ),
        migrations.RemoveField(
            model_name='basic_detail',
            name='FacebookLink',
        ),
        migrations.RemoveField(
            model_name='basic_detail',
            name='LinkedIN',
        ),
        migrations.RemoveField(
            model_name='basic_detail',
            name='TwitterLink',
        ),
        migrations.RemoveField(
            model_name='basic_detail',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='basic_detail',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='basic_detail',
            name='mobile_number',
        ),
    ]
