# Generated by Django 3.0.8 on 2020-08-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapps', '0002_auto_20200804_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_detail',
            name='Designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basic_detail',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basic_detail',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basic_detail',
            name='mobile_number',
            field=models.IntegerField(null=True),
        ),
    ]
