# Generated by Django 3.0.8 on 2020-08-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapps', '0003_auto_20200804_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_detail',
            name='CompanyCategory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basic_detail',
            name='CompanyRevenue',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basic_detail',
            name='CompanySize',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basic_detail',
            name='CompanyType',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basic_detail',
            name='FacebookLink',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basic_detail',
            name='LinkedIN',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='basic_detail',
            name='TwitterLink',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
