# Generated by Django 3.0.8 on 2020-08-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapps', '0004_auto_20200804_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRSTNAME', models.CharField(max_length=100, null=True)),
                ('LASTNAME', models.CharField(max_length=100, null=True)),
                ('DATE', models.CharField(max_length=100, null=True)),
                ('MONTH', models.CharField(max_length=100, null=True)),
                ('YEAR', models.CharField(max_length=100, null=True)),
                ('phonenumber', models.CharField(max_length=100, null=True)),
                ('emailid', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='basic_detail',
        ),
    ]
