# Generated by Django 3.0.8 on 2020-08-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapps', '0005_auto_20200819_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='other_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FATHERNAME', models.CharField(max_length=100, null=True)),
                ('MOTHERNAME', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('Zip', models.CharField(max_length=100, null=True)),
                ('Aadharnumber', models.CharField(max_length=100, null=True)),
                ('Driverlicense', models.CharField(max_length=100, null=True)),
                ('emergencycontactno2', models.CharField(max_length=100, null=True)),
                ('emergencycontactno1', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
