# Generated by Django 3.0.8 on 2020-08-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapps', '0007_auto_20200820_1111'),
    ]

    operations = [
        migrations.DeleteModel(
            name='other_details',
        ),
        migrations.AddField(
            model_name='employee_registration',
            name='DATE',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee_registration',
            name='MONTH',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee_registration',
            name='YEAR',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
