# Generated by Django 3.0.8 on 2020-08-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapps', '0008_auto_20200820_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_salary_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, null=True)),
                ('salary', models.CharField(max_length=100, null=True)),
                ('DATE', models.CharField(max_length=100, null=True)),
                ('MONTH', models.CharField(max_length=100, null=True)),
                ('YEAR', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
