# Generated by Django 3.0.8 on 2020-08-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapps', '0010_employee_registration_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee_salary_details',
        ),
        migrations.AlterField(
            model_name='employee_registration',
            name='GENDER',
            field=models.BooleanField(max_length=100, null=True, verbose_name='GENDER'),
        ),
    ]
