# Generated by Django 3.0.8 on 2020-08-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapps', '0011_auto_20200821_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_salary_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100, null=True)),
                ('salary', models.CharField(max_length=100, null=True)),
                ('DATE', models.CharField(max_length=100, null=True)),
                ('MONTH', models.CharField(max_length=100, null=True)),
                ('YEAR', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='other_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FATHERNAME', models.CharField(max_length=100, null=True)),
                ('MOTHERNAME', models.CharField(max_length=100, null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('Zip', models.CharField(max_length=100, null=True)),
                ('Aadharnumber', models.CharField(max_length=100, null=True)),
                ('Driverlicense', models.CharField(max_length=100, null=True)),
                ('emergencycontactno2', models.CharField(max_length=100, null=True)),
                ('emergencycontactno1', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
