# Generated by Django 3.0.8 on 2020-08-22 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapps', '0013_auto_20200821_2008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='employee_salary_details',
        ),
    ]
