# Generated by Django 3.0.8 on 2020-08-22 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapps', '0014_delete_employee_salary_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ed_det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=100, null=True)),
                ('qualification', models.CharField(max_length=100, null=True)),
                ('institution', models.CharField(max_length=100, null=True)),
                ('year', models.CharField(max_length=100, null=True)),
                ('percentage', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
