# Generated by Django 3.0.8 on 2020-08-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapps', '0016_employee_salary_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='bank_det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountnumber', models.CharField(max_length=100, null=True)),
                ('ifsccode', models.CharField(max_length=100, null=True)),
                ('bankname', models.CharField(max_length=100, null=True)),
                ('bankaddress', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
