# Generated by Django 3.0.8 on 2020-08-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapps', '0018_user_man'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_man',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee_registration',
            name='GENDER',
            field=models.CharField(max_length=100, null=True, verbose_name='GENDER'),
        ),
    ]
