# Generated by Django 3.0.8 on 2020-08-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapps', '0019_auto_20200824_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='ex_det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.CharField(max_length=100, null=True)),
                ('to_date', models.CharField(max_length=100, null=True)),
                ('position', models.CharField(max_length=100, null=True)),
                ('reason', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='ed_det',
            old_name='institution',
            new_name='institute',
        ),
        migrations.RenameField(
            model_name='ed_det',
            old_name='percentage',
            new_name='percent',
        ),
        migrations.RemoveField(
            model_name='ed_det',
            name='sno',
        ),
        migrations.AlterField(
            model_name='employee_registration',
            name='GENDER',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
