# Generated by Django 3.0.8 on 2020-08-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapps', '0021_ex_det_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliername', models.CharField(max_length=100, null=True)),
                ('companyname', models.CharField(max_length=100, null=True)),
                ('phonenumber', models.CharField(max_length=100, null=True)),
                ('emailid', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tab2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=100, null=True)),
                ('City', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('Zipcode', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='bank_det',
        ),
        migrations.DeleteModel(
            name='ed_det',
        ),
        migrations.DeleteModel(
            name='employee_registration',
        ),
        migrations.DeleteModel(
            name='employee_salary_details',
        ),
        migrations.DeleteModel(
            name='ex_det',
        ),
        migrations.DeleteModel(
            name='other_detail',
        ),
        migrations.DeleteModel(
            name='user_man',
        ),
    ]
