# Generated by Django 3.1.1 on 2020-09-09 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapps', '0024_auto_20200909_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_registration',
            old_name='date',
            new_name='dob',
        ),
    ]
